version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys: # add SSH key with write access
          fingerprints:
            - "fb:1e:06:f0:5c:e9:d4:31:9a:1c:8a:62:03:cd:07:a0"
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install yarn
          command: sudo npm install -g yarn
      -run:
          name: Install dependencies
          command: && sudo yarn install --frozen-lockfile
      - run:
          name: Publish update to GitHub
          command: sudo bash ./deploy.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: dev
